### ISSUE TITLE
Fix last front end details

### ISSUE THREAD

**Issue by fricoben** [starknet-id/sbtmaker.starknet.id#24]
The goal here is to change the problems that we have on the front-end. 

## 1) The connection Modal

Starknet id aims to use the same components over all its apps. It includes sbt.starknet.id so we'll need to change the modal connection form in order to make it look like the one we use all over our apps.

**The current modal that we have**

<img width="200" alt="Capture d’écran 2023-02-07 à 15 24 12" src="https://user-images.githubusercontent.com/78437165/217274680-ffde319e-92f4-47e8-84ce-63f2ff3108da.png">

**What we want**

<img width="200" alt="Capture d’écran 2023-02-07 à 15 36 55" src="https://user-images.githubusercontent.com/78437165/217274762-38f2155a-64e2-41af-85e9-d40c3baddd20.png">

## 2) Some small fixes

<img width="135" alt="Capture d’écran 2023-02-07 à 15 30 40" src="https://user-images.githubusercontent.com/78437165/217277082-f7f1e299-0744-4ab9-a033-52888db9aa43.png">

<img width="870" alt="Capture d’écran 2023-02-07 à 15 27 46" src="https://user-images.githubusercontent.com/78437165/217277070-940008e0-aed5-4b21-9f5c-969f8ce1e328.png">

A) Here we want to vertically center the block + we don't want to refer to poapp on the app right now but we want to refer as an sbt.

B) Plus I think it's better to delete the password feature for the moment, the end goal is to have a public/whitelisted mint feature with a max date. For the moment having only a public mint with max date will be easier for everyone imo so no need to ask for the password.

## 3) Add a success component 

We'll need to add success, instead of showing this 

<img width="481" alt="Capture d’écran 2023-02-07 à 16 23 19" src="https://user-images.githubusercontent.com/78437165/217288017-21902c55-6909-425a-9203-c3cccf704be5.png">

We should be able to see a title **SUCCESS** and a text that gives the deployed contract address if you can or if not the transaction hash with the link to Starkscan will do the work.

## More info 

This PR will take around 2 hours imo. @Marchand-Nicolas would be the best to do it as he did most of the work.

**Comment by Marchand-Nicolas** [comment]
I am going to do the PR soon

**Comment by Marchand-Nicolas** [comment]
#26
