### ISSUE TITLE
Minting website generator

### ISSUE THREAD

**Issue by fricoben** [starknet-id/sbtmaker.starknet.id#25]
## What we want

Currently the repo permits deploying an SBT contract like so, but in order for this site to be a Real no-code, users should also be able to create their own minting app. For the moment we'll keep it simple, the idea is to keep the same front-end that the first SBT app ([hackerhouse.starknet.id](https://hackerhouse.starknet.id)) but for any SBT contract. 

## How we see it

You'll need to create a page that can read the data of an SBT contract and show the image, and verify the password automatically. So you'll have the in query params the address of the SBT contract and you'll be able to get all the info needed to build your page. It should show if the mint is closed and the image of the SBT you're minting, the main difference that we'll have with hackerhouse.starknet.id is that we won't need any password here. 

The private key could be generated on the front end as we did in hackerhouse.starknet.id, at some point we'll use the wallet connected to do so.

I think this PR could take around 2-3 days depending on your level and your knowledge about the SBT contract.

## More context and contact

[Here is the repo](https://github.com/starknet-id/hackerhouse.starknet.id) of hackerhouse.starknet.id
[Here is the repo](https://github.com/starknet-id/identity_tokens) of the SBT contract it'll soon change but it's not a problem.

**Comment by irisdv** [comment]
Can work on this issue

**Comment by fricoben** [comment]
the chad Iris took it
