### ISSUE TITLE
Error when trying to mint a SBT from a contract deployed on testnet through sbt.starknet.id

### ISSUE THREAD

**Issue by irisdv** [starknet-id/sbtmaker.starknet.id#28]
When deploying a SBT contract on testnet through sbt.starknet.id, deployment works well but I get an error when trying to mint an SBT : 
`Requested contract address 0x5dbdedc203e92749e2e746e2d40a768d966bd243df04a6b712e222bc040a9af is not deployed.`

This address corresponds to the `Starknet.id: Identity` contract on mainnet.

**Comment by fricoben** [comment]
mmmmh on testnet is goerli.sbt.starknet.id

**Comment by fricoben** [comment]
I check the env variables are ok for the `goerli.app.starknet.id` website

**Comment by fricoben** [comment]
Saw with Iris it's a misunderstanding
